// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyhcmtdppcxslyzfuqvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5aGNtdGRwcGN4c2x5emZ1cXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Mjk0MDEsImV4cCI6MjA3MDMwNTQwMX0.xP7K2FYmTaTqb7INL-dBag6yP6ey6s8xv2w4aSLQJdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  }
});